name: ğŸ§ª End-to-End Testes CTFL

on:
  workflow_dispatch:

jobs:
  exam1-tests:
    name: ğŸ”¹ Exam 1
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ InstalaÃ§Ã£o de dependÃªncias
        run: npm install

      - name: ğŸš€ Executar testes do exam1
        run: npm run run:exam1

  exam2-tests:
    name: ğŸ”¸ Exam 2
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ InstalaÃ§Ã£o de dependÃªncias
        run: npm install

      - name: ğŸš€ Executar testes do exam2
        run: npm run run:exam2

  exam3-tests:
    name: ğŸ”» Exam 3
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ InstalaÃ§Ã£o de dependÃªncias
        run: npm install

      - name: ğŸš€ Executar testes do exam3
        run: npm run run:exam3
